version: "3.8"
services:
  node:
    build: .
    env_file: ./.env
    command: npm start
    volumes:
      - .:/app/
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongo
    environment:
      MYSQL_HOST: mongo
  mongo:
    image: mongo
    env_file: ./.env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./src/learn/config/mongod.conf:/etc/mongod.conf
      - ./src/learn/files:/app/
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
